config/routes.rb
Rightpeopleforthejob::Application.routes.draw do

  resources :partners

  resources :teams

  resources :testscaffolds

  resources :filter_analytics

  resources :contact_feewises

  resources :bulletins

  resources :discount_codes

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :us

  resources :subscriptions

  resources :purchase_preferences

  resources :accounts

  resources :cards

  devise_for :users, :controllers  => { :registrations => 'my_devise/registrations' }

  mount Split::Dashboard, :at => 'split'

  get "static_pages/create"

  get "static_pages/support"
  get "static_pages/purchase"
  get "static_pages/partners"
  get "static_pages/investors"
  get "static_pages/careers"

  get "static_pages/why_feewise"
  get "static_pages/terms_of_use"
  get "static_pages/sign_up"
  get "static_pages/sign_in"
  get "static_pages/forgot"

  get "static_pages/privacy_policy"
  get "static_pages/how_it_works"
  get "static_pages/about_us"
  get "static_pages/thank_you"
  get "static_pages/equal_housing_opportunity"

  get "static_pages/team"
  get "homes/home_a"
  get "homes/home_b"

  get "static_pages/run_restart"

  resources :static_pages
  resources :agents

  authenticated :user do
    root :to => 'static_pages#index'
  end
  root :to => 'static_pages#index'

  match ':action' => 'static_pages#:action'

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  attr_accessible :placeholder
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_filter :not_in_procee_of_buying, :except => [:terms_of_use, :privacy_policy, :index]

  # before_filter :allocate_subscription_for_emails

  # GET /static_pages
  # GET /static_pages.json
  def index

    session[:style] = nil if params.values.find_index "clear"
    @static_pages = []# StaticPage.all
     #?? wtf is this?

    @video = '8Cx875BeRPI'

    if session[:feewise_inproc_buying] && current_user # logged in
      @purchase_preference = current_user.purchase_preference ? current_user.purchase_preference : PurchasePreference.new
      # redirect_to eval("#{session[:feewise_steps][2]} @purchase_preference") and return
      # redirect_to eval(PurchaseFlow.step_path(2, @purchase_preference)) and return
      redirect_to PurchaseFlow.step_path(2, @purchase_preference) and return
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @static_pages }
    end
  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  # def show
  #   @static_page = StaticPage.find(params[:id])

  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.json { render json: @static_page }
  #   end
  # end

  # GET /static_pages/new
  # GET /static_pages/new.json
  def new
    @static_page = StaticPage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @static_page }
    end
  end

  # GET /static_pages/1/edit
  def edit
    @static_page = StaticPage.find(params[:id])
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(params[:static_page])

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: 'Static page was successfully created.' }
        format.json { render json: @static_page, status: :created, location: @static_page }
      else
        format.html { render action: "new" }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /static_pages/1
  # PUT /static_pages/1.json
  def update
    @static_page = StaticPage.find(params[:id])

    respond_to do |format|
      if @static_page.update_attributes(params[:static_page])
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page = StaticPage.find(params[:id])
    @static_page.destroy

    respond_to do |format|
      format.html { redirect_to static_pages_url }
      format.json { head :no_content }
    end
  end

  def why_feewise
  end

  def terms_of_use
  end

  def support
  end

  def sign_up
    redirect_to(new_user_registration_path)
  end

  def sign_in
    redirect_to(new_user_session_path)
  end

  def forgot
    redirect_to(new_password_path(:user))
  end

  def purchase
  end

  def privacy_policy
  end

  def partners
  end

  def investors
  end

  def how_it_works
  end

  def careers
  end

  def about_us
  end

  def thank_you
  end

  def team
  end

  def home_a
  end

  # def run_restart
  # end

  # def do_the_restart
  #   puts "Graceful Volume Squared Shutdown"
  #   exit
  #   # begin
  #   #   `run heroku restart`
  #   # rescue Exception => e
  #   # end
  # end

# def F123
#     redirect_to 'https://www.feewise.com/?utm_source=charles_test&utm_medium=campaign_business_card_test&utm_campaign=campaign_test'
#   # redirect_to 'http://www.web.com/myurl', :overwrite_params => { :parm => 'foo' }
# end

  private

  def not_in_procee_of_buying
    session[:feewise_inproc_buying] = false
  end

  # def allocate_subscription_for_emails
  #   @subscription = Subscription.new
  # end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  # def display_heading(locals = {})
  #   locals.reverse_merge! :heading_text => 'FeeWise'
  #   render :partial => 'static_pages/page_head', :locals => locals
  # end
end

app/views/static_pages/_accordion.html.erb
<style type="text/css" media="screen">
  .ui-helper-reset {
  font-size: 110%;
  }
  .ui-state-default a, .ui-state-default a:link, .ui-state-default a:visited {
  color: #4169E1;
  }
  .ui-state-active a, .ui-state-active a:link, .ui-state-active a:visited {
  color: #4169E1;
  }
</style>


  <div class='well'>

    <div class="jqui_accordion">
      <h3><a href="#"> What is feeWISE?</a></h3>
      <div>

        <p> FeeWISE is your guide to being a more savvy home buyer and/or seller.<br />
          What you don't know can cost you.  Fortunately, what you do know can save you a bundle.</p>
      </div>

      <h3><a href="#"> How does it work?</a></h3>
      <div>

        <p>We take you through the process step-by-step.</p>
        We teach you how to think about each aspect of the process an easy and understandable way. <br />
        Complex topics are broken down into short email courses.<br /><br />
        <p>We can connect you to anyone you need.</p>
      </div>

      <h3><a href="#">How You Save</a></h3>
      <div>

        <p>We explain:</p>
        <ul>
          <li> the garbage fees you can avoid</li>
          <li> Other money saving strategies used by the pros</li>
        </ul>
        <p>We show you how to determine:</p>
        <ul>
          <li>What professionals you need, and in what circumstances</li>
          <li>How to pick your providers - and keep them accountable</li>
        </ul>
      </div>

      <h3><a href="#">Get Paid by Us</a></h3>
      <div>

        <p> Complete a transaction following our process from start to finish and get a check from us.<br />
          Best of all, you will know exactly how we - and you - did it.</p>
      </div>

      <h3><a href="#">Getting Started is Easy</a></h3>
      <div>

        <p>Answer some basic questions.<br />
          If you have any, ask us.</p>
      </div>

      <h3><a href="#">Be feeWISE Now</a></h3>
      <div>

        <p>If you are serious about getting yourself the best possible outcome, then feeWISE was made for you.</p>
        <p>When you are all done, you can be proud of yourself for being far more savvy than most.</p>
        <p>Not satisfied? Just let us know and we will refund your membership fee. So there's no risk.<br />
          In fact, the risk you're already taking is going down. You will have a better sense what is happening. <%= link_to 'BUY!', new_account_path, :class => "btn btn-warning  btn-large whitelink" %></p>

				<p></p>
				
        <br />
      </div>
    </div> <!-- .jqui_accordion -->

  </div>

app/views/static_pages/_career_sidebar.html.erb
<div id="sidebar">
  <div class="sb-item">
    <%= t ".fe_careers_sidebar", default: "New combined careers sidebar" %> 
  </div>
</div>

app/views/static_pages/_goanimate_video.html.erb
<a href="http://goanimate.com/videos/0umoZWT5Y02I?utm_source=embed&uid=0LRj8nZZY5qk" target="_blank"></a>  <a href="http://goanimate.com/user/0LRj8nZZY5qk" target="_blank"></a>  <a href='http://goanimate.com?utm_source=embed' target="_blank"></a><br/><iframe scrolling="no" allowTransparency="true" frameborder="0" width="400" height="225" src="http://goanimate.com/player/embed/0umoZWT5Y02I"></iframe><br/><a href="http://goanimate.com?utm_source=embed&utm_medium=link&utm_term=Video+Maker&utm_campaign=embedse" target="_blank"></a>

app/views/static_pages/_page_head.html.erb
<!-- BEGIN PAGE-HEAD ####################-->

<div id="pageHead">

  <div id="title-area">

      <% if current_user.try(:admin?) %>
        <h2 class="alignCenter"><%= heading_text %></h2>
        <ul id="navAdminXXXX" >
          <li><%= link_to "Buyers", accounts_path %> </li>
          <li><%= link_to "Sellers", accounts_path %> </li>
          <li><%= link_to "Shortener", us_path %> </li>
          <li><%= link_to "Discounts", accounts_path %> </li>
          <li><%= link_to "Banks", "#" %> </li>
          <li><%= link_to "Title Insurance", "#" %> </li>
        </ul>
      <% end %>


    <div id="title-content">
      <% if ! current_user.try(:admin?) %>
        <h1><%= heading_text %></h1>
        <% end %>
    </div>

  </div>





</div>

<!-- END PAGE-HEAD ####################-->

app/views/static_pages/_sidebar.html.erb
<!-- <div id="sidebar"> -->
<!--   <div class="sb-item"> -->
<!--     < %= image_tag "badge-guaranteed.jpg", class: "floatRight" %> -->
<!--     < %= t ".fe_main_sidebar", default: "<h3>The FeeWise Pledge</h3><p>If the experience using your FeeWise ever lets you down, we'll make it right or refund your purchase. Simple as that.</p><br /><h3>We're Here for You</h3><p>If you want to talk to someone, call us at 917-720-4242. Also, check out our FAQ for answers to some questions.</p>" %> -->
<!--   </div> -->
<!-- </div> -->

app/views/static_pages/_sticky_footer.html.erb
<%= t ".fe_body_for_sticky_footer", default: "here is the body for sticky_footer" %>
<%= render :partial => "layouts/mailing_list_well" %>
<%= t ".fe_body_for_post_mailer_sticky_footer", default: "" %>

app/views/static_pages/_terms_and_privacy.html.erb
          * I agree to the
          <%= link_to "Terms of Use", "/terms_of_use" %>
          and
          <%= link_to "Privacy Policy", "/privacy_policy" %>

app/views/static_pages/_twitter_and_fb.html.erb
  <div id="offer-share">
    <div class="label"><strong>Share:</strong></div>
    <%= link_to image_tag("offer-icon-facebook.gif", {title: "Like us on Facebook", alt: "Facebook", class: "social-icons"} ), "http://www.facebook.com/feeWISE" %>
    <%= link_to image_tag("offer-icon-twitter.gif",  title: "Follow us on Twitter", alt: "Twitter", class: "social-icons"), "http://twitter.com/feewise" %>
  </div>

app/views/static_pages/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<!-- <p> -->
<!--   <b>Placeholder:</b> -->
<!-- < %= @static_page.placeholder %> -->
<!-- <h1>You are trying to show.html.erb a Static Page.  This is a bug in transation from design version of feewise to rails version</h1> -->
<!-- </p> -->

app/views/static_pages/sign_in.html.erb

<%= display_heading :heading_text => 'Sign In' %>
<!-- BEGIN CONTENT ####################-->
<div id="content" style="">
  <div id="content-body">
    <%= render :partial => "static_pages/generic_sidebar" %>
    <div class="one-col"><!-- --></div>
    <div class="five-col">
      <form action="account.html">
        <div><label>Email</label></div>
        <div class="input-div"><input size="40" type="text" name="" class="input-text" /></div>

        <div><label>Password</label></div>
        <div class="input-div"><input size="40" type="password" name="" class="input-text" /><div><a href="" class="smTxt">Forgot your password?</a></div></div>
        <div class="btn-submit"><input type="submit" name="" value="" id="btn-signIn" /></div>
        <div class="btn-altLink"><a href="sign_up.html" class="smTxt">Not yet a member?</a></div>
      </form>
    </div>
  </div>
  <br class="clearBoth" />
</div>
<!-- END CONTENT ####################-->

app/views/static_pages/support.html.erb
<!-- BEGIN PAGE-HEAD ####################-->
<div id="pageHead">
  <div id="title-area">
    <div id="title-content"><h1>Support/FAQ</h1></div>
  </div>
</div>
<!-- END PAGE-HEAD ####################-->


<!-- BEGIN CONTENT ####################-->
<div id="content" style="">
  <div id="content-body">
    <%= render :partial => "static_pages/generic_sidebar" %>
    <div class="one-col"><!-- --></div>
    <div class="five-col">
      <%= t ".fe_support_faq", default: "You can call us at 917-720-4242. Also, please feel free to email us at be@feewise.com for additional support." %>

      <%= link_to "Click", new_contact_feewise_path %> to email us with more questions.

    </div>
  </div>
  <br class="clearBoth" />
</div>


<br />



<!-- END CONTENT ####################-->

app/views/static_pages/team.html.erb
<%= display_heading :heading_text => 'The Team' %>
<!-- BEGIN CONTENT ####################-->
<div id="content" style="">
  <div id="content-body">
    <!-- < %= render :partial => "static_pages/generic_sidebar" %> -->
    <div class="one-col"><!-- --></div>
    <div class="five-col">

    <%= t ".fe_the_team", default: "All about the people standing behind you." %>

    </div>
  </div>
  <br class="clearBoth" />
</div>
<!-- END CONTENT ####################-->

app/views/static_pages/thank_you.html.erb
<%= display_heading :heading_text => 'Thank You!' %>

<!-- < %= render :partial => "static_pages/generic_sidebar" %> -->

<%= t ".fe_thank_you_1", default: "Your order was successfully processed." %>
<%= t ".fe_thank_you_2", default: "Congratulations on taking your first step towards saving a boatload on your next home. Meanwhile, feel free to shout out at the top of your lungs, and share with your friends on what an amazing deal you just scored!" %>

<br /><br />

<!-- <p> -->
<!--   <a href="http://www.facebook.com/feeWISE" target="_blank"> -->
<!--     <img src="/assets/lg-icon-facebook.jpg" title="Like us on Facebook" alt="Facebook" class="social-icons" /></a> -->
<!--   <a href="http://twitter.com/feewise" target="_blank"> -->
<!--     <img src="/assets/lg-icon-twitter.jpg" title="Follow us on Twitter" alt="Twitter" class="social-icons" /></a> -->
<!-- </p> -->



<br />
<p>
  <%= link_to 'Continue', account_path(current_user.account), :class => "btn btn-primary btn-large" %> Click Continue and start working through the Checklist.  
</p>
<br />

<script type="text/javascript">
  _kmq.push(['record', 'Conversion']);
</script>



<!-- Your order was successfully processed. We look forward to helping you -->
<!-- achieve and save on your real estate goals.  -->

<!-- The next step is to talk with one of our Experts to guide you in building your team. -->

<!-- Please let us know the best times to have one of our team building professionals contact you. -->




<!-- Expect a welcome call from us! Congratulations on taking your first step towards being a smarter -->
<!-- savvier home buyer.  -->


<!-- We look forward to helping you save.  -->



<!-- Meanwhile, please let those you know who also want to buy soon know about -->
<!-- feeWISE! -->

app/views/static_pages/why_feewise.html.erb

<%= display_heading :heading_text => 'Why feeWISE' %>
<!-- BEGIN CONTENT ####################-->
<div id="content" style="">
  <div id="content-body">
    <%= render :partial => "static_pages/generic_sidebar" %>

    <div class="one-col"><!-- --></div>
    <div class="five-col">

      <%= t ".fe_why_feewise", default: "<p><strong>Why feeWISE? Because the fees are too d@mn high. And the consequences can be an enormous cost to you!</strong></p><p>Our approach is simple, we simply put you&#8212;the customers first&#8212;ahead of the commissions. Plenty of home buyers received less than completely honest advice, because certain professionals prey upon your confusion with the complexity of the real estate market. That's why feeWISE is here. We believe that home-buying should be simpler, less stressful, and cheaper for buyers and sellers. We measure our success not by our bottom line, but by how much we save and put back into your pocket.</p>" %>

    </div>
  </div>
  <br class="clearBoth" />
</div>
<!-- END CONTENT ####################-->