config/routes.rb
Rightpeopleforthejob::Application.routes.draw do

  resources :partners

  resources :teams

  resources :testscaffolds

  resources :filter_analytics

  resources :contact_feewises

  resources :bulletins

  resources :discount_codes

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :us

  resources :subscriptions

  resources :purchase_preferences

  resources :accounts

  resources :cards

  devise_for :users, :controllers  => { :registrations => 'my_devise/registrations' }

  mount Split::Dashboard, :at => 'split'

  get "static_pages/create"

  get "static_pages/support"
  get "static_pages/purchase"
  get "static_pages/partners"
  get "static_pages/investors"
  get "static_pages/careers"

  get "static_pages/why_feewise"
  get "static_pages/terms_of_use"
  get "static_pages/sign_up"
  get "static_pages/sign_in"
  get "static_pages/forgot"

  get "static_pages/privacy_policy"
  get "static_pages/how_it_works"
  get "static_pages/about_us"
  get "static_pages/thank_you"
  get "static_pages/equal_housing_opportunity"

  get "static_pages/team"
  get "homes/home_a"
  get "homes/home_b"

  get "static_pages/run_restart"

  resources :static_pages
  resources :agents

  authenticated :user do
    root :to => 'static_pages#index'
  end
  root :to => 'static_pages#index'

  match ':action' => 'static_pages#:action'

end

app/controllers/contact_feewises_controller.rb
class ContactFeewisesController < InheritedResources::Base
  after_filter :finish_ab_test, :only => [:create]
end

app/helpers/contact_feewises_helper.rb
module ContactFeewisesHelper
end

app/views/contact_feewises/_form.html.erb
<%= form_for(@contact_feewise) do |f| %>
  <% if @contact_feewise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_feewise.errors.count, "error") %> prohibited this contact_feewise from being saved:</h2>

      <ul>
        <% @contact_feewise.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table border="0" cellspacing="5" cellpadding="5">
    <tr>
      <td> <%= f.submit "Send", :class => "btn btn-primary" %> </td>
      <td> <%= link_to "Cancel", new_contact_feewise_path, :class => "btn", :style => "color:#000;" %> </td>
      <td>
        <span>Subject Category: <%= f.select :label, [["Help Buy","Help Buy"], ["Site Suggestion","Site Suggestion"], ["Compliment","Compliment"], ["Critique","Critique"], ["Other","Other"] ], {:include_blank => true} %></span>
      </td>
    </tr>
  </table>

  <table border="0" cellspacing="5" cellpadding="5">
    <tr>
      <td> To </td>
      <td> <%= f.text_field :to , :class => 'input-text', :placeholder => "founders@feewise.com", :style =>"margin: 0px; width: 500px;",:readonly => true %> </td>
    </tr>
    <tr>
      <td> Cc </td>
      <td> <%= f.text_field :cc, :class => 'input-text', :style =>"margin: 0px; width: 500px;" %> </td>
    </tr>
    <tr>
      <td> From </td>
      <td> <%= f.text_field :email, :class => 'input-text', :style =>"margin: 0px; width: 500px;", :placeholder => "Needed for an answer" %> </td>
    </tr>
    <tr>
      <td> Subject </td>
      <td> <%= f.text_field :subject, :class => 'input-text', :style =>"margin: 0px; width: 500px;" %> </td>
    </tr>
  </table>

  <%= f.text_area :body, :class => 'input-text', :style =>"margin: 0px; width: 574px; height: 274px;" %>

  <%= f.hidden_field :user_id %>

<% end %>

app/views/contact_feewises/edit.html.erb
<h1>Editing contact_feewise</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_feewise %> |
<%= link_to 'Back', contact_feewises_path %>

app/views/contact_feewises/index.html.erb
<h1>Listing contact_feewises</h1>

<table>
  <tr>
    <th>To</th>
    <th>Cc</th>
    <th>Subject</th>
    <th>Body</th>
    <th>Label</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contact_feewises.each do |contact_feewise| %>
  <tr>
    <td><%= contact_feewise.to %></td>
    <td><%= contact_feewise.cc %></td>
    <td><%= contact_feewise.subject %></td>
    <td><%= contact_feewise.body %></td>
    <td><%= contact_feewise.label %></td>
    <td><%= contact_feewise.user_id %></td>
    <td><%= link_to 'Show', contact_feewise %></td>
    <td><%= link_to 'Edit', edit_contact_feewise_path(contact_feewise) %></td>
    <td><%= link_to 'Destroy', contact_feewise, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact feewise', new_contact_feewise_path %>

app/views/contact_feewises/new.html.erb
<!-- <h1>New contact_feewise</h1> -->
<!-- < %= render 'form' %> -->
<!-- < %= link_to 'Back', contact_feewises_path %> -->

<%= display_heading :heading_text => 'Email Us' %>

<!-- BEGIN CONTENT ####################-->
<div id="content" style="">
  <div id="content-body">
    <!-- < %= render :partial => "static_pages/generic_sidebar" %> -->
    <div class="one-col"><!-- --></div>
    <div class="five-col">
      <!-- <p> < %= t ".fe_email_us_message", default: "Tell us what you think and be entered into a chance for a bottle of bubbly" %> </p> -->

      <%= render 'form' %>

    </div>
  </div>
  <br class="clearBoth" />
</div>
<!-- END CONTENT ####################-->

app/views/contact_feewises/show.html.erb
<%= display_heading :heading_text => 'Thank You!' %>
<!-- BEGIN CONTENT ####################-->
<div id="content" style="">
  <div id="content-body">
    <%= render :partial => "static_pages/generic_sidebar" %>
    <div class="one-col"><!-- --></div>
    <div class="five-col">
      <%= t ".fe_thank_you_email", default: "Thank you for sending us an enquiry." %>
      <br />      <br />
      <p>
        <a href="http://www.facebook.com/feeWISE" target="_blank">
          <img src="/assets/lg-icon-facebook.jpg" title="Like us on Facebook" alt="Facebook" class="social-icons" /></a>
        <a href="http://twitter.com/feewise" target="_blank">
          <img src="/assets/lg-icon-twitter.jpg" title="Follow us on Twitter" alt="Twitter" class="social-icons" /></a>
      </p>

      <!-- <p>< %= link_to image_tag( "btn-myAccount.gif", :title => "Go to My Account", :class => "button", :alt=>"Go to My Account"), purchase_preference_path(current_user.purchase_preference) %></p> -->

    </div>
  </div>
  <br class="clearBoth" />
</div>
<!-- END CONTENT ####################-->
<script type="text/javascript">
  _kmq.push(['record', 'Conversion']);
</script>