config/routes.rb
Rightpeopleforthejob::Application.routes.draw do

  resources :partners

  resources :teams

  resources :testscaffolds

  resources :filter_analytics

  resources :contact_feewises

  resources :bulletins

  resources :discount_codes

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :us

  resources :subscriptions

  resources :purchase_preferences

  resources :accounts

  resources :cards

  devise_for :users, :controllers  => { :registrations => 'my_devise/registrations' }

  mount Split::Dashboard, :at => 'split'

  get "static_pages/create"

  get "static_pages/support"
  get "static_pages/purchase"
  get "static_pages/partners"
  get "static_pages/investors"
  get "static_pages/careers"

  get "static_pages/why_feewise"
  get "static_pages/terms_of_use"
  get "static_pages/sign_up"
  get "static_pages/sign_in"
  get "static_pages/forgot"

  get "static_pages/privacy_policy"
  get "static_pages/how_it_works"
  get "static_pages/about_us"
  get "static_pages/thank_you"
  get "static_pages/equal_housing_opportunity"

  get "static_pages/team"
  get "homes/home_a"
  get "homes/home_b"

  get "static_pages/run_restart"

  resources :static_pages
  resources :agents

  authenticated :user do
    root :to => 'static_pages#index'
  end
  root :to => 'static_pages#index'

  match ':action' => 'static_pages#:action'

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name
  validates_presence_of :email
  validates_uniqueness_of :email

  after_create :send_presales_customer_enquiry, :subscribe_to_mailchimp_subscriptions

private
# todo: do the email when it is time to debug
  def send_presales_customer_enquiry
    UserMailer.presales_customer_enquiry( self.email ).deliver
  end

  def subscribe_to_mailchimp_subscriptions
    Rails.logger.warn "** Subscribe #{self.email}to mailchimp status #{MailChimpMailer.subscribe("Your home search savings leader",self.email,self.first_name, self.last_name)}"
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  after_filter :finish_ab_test, :only => [:create]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscriptions }
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/new
  # GET /subscriptions/new.json
  def new
    @subscription = Subscription.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/1/edit
  def edit
    @subscription = Subscription.find(params[:id])
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(params[:subscription])

    if @subscription.save
      redirect_to root_path, notice: "Thank you for subscribing."
    else
      flash[:warning] = 'Please correct email address etc. for newsletter and resubmit.'
      redirect_to root_path
    end
    
  end


  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to subscriptions_url }
      format.json { head :no_content }
    end
  end



end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% @subscription.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <!-- < %= f.label :email %><br /> -->
    <%= f.text_field :email, :class => "input-text", :placeholder => "Enter your email & hit return"  %>
  </div>

  <!-- <div class="actions"> -->
  <!--   < %= f.submit "Join Mailing List", :class => 'btn'  %> -->
  <!-- </div> -->


  <%= link_to(new_subscription_path, :class => 'btn btn-large btn-success whitelink') do %>
    Join Mailing List <i class="icon-envelope icon-white"></i>
  <% end %>


<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscriptions.each do |subscription| %>
  <tr>
    <td><%= subscription.email %></td>
    <td><%= link_to 'Show', subscription %></td>
    <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
    <td><%= link_to 'Destroy', subscription, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'subscriptions/form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @subscription.email %>
</p>


<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>